do_20*: run like real script (and corresponding updates in run_20*)

diff --git a/scripts/do_20_ap_simple b/scripts/do_20_ap_simple
--- a/scripts/do_20_ap_simple
+++ b/scripts/do_20_ap_simple
@@ -15,28 +15,129 @@ set ecode = 0
 # ---------------------------------------------------------------------------
 
 # labels
-set dir_basic      = $1                # INPUT group level dir
-set dir_ap         = $2                # OUTPUT group level dir
-set subj           = $3
-set ses            = $4
-set ap_label       = 20_ap_simple
+set dir_input      = ""                # INPUT group level dir
+set dir_ap         = ""                # OUTPUT group level dir
+set subj           = ""                # req subject ID 
 
-if ( "${subj}" == "" ) then
-    echo "** ERROR: need 3 or 4 command line args:"
-    echo "       DIR_INPUT  DIR_OUTPUT  SUBJ [SES]"
-    exit 1
+set ses            = ""                # opt session level ID 
+set task_label     = ""                # opt label, to get subset of data
+
+set template = "MNI152_2009_template_SSW.nii.gz"  # def template for proc
+
+
+# ------------------- process options, a la rr ----------------------
+
+if ( $#argv == 0 ) goto SHOW_HELP
+
+set ac = 1
+while ( $ac <= $#argv )
+    # terminal options
+    if ( ("$argv[$ac]" == "-h" ) || ("$argv[$ac]" == "-help" )) then
+        goto SHOW_HELP
+    endif
+    if ( "$argv[$ac]" == "-ver" ) then
+        goto SHOW_VERSION
+    endif
+
+    if ( "$argv[$ac]" == '-echo' ) then
+        set echo
+
+    # --------- required
+
+    else if ( "$argv[$ac]" == "-dir_input" ) then
+        if ( $ac >= $#argv ) goto FAIL_MISSING_ARG
+        @ ac += 1
+        set dir_input = "$argv[$ac]"
+
+    else if ( "$argv[$ac]" == "-dir_output" ) then
+        if ( $ac >= $#argv ) goto FAIL_MISSING_ARG
+        @ ac += 1
+        set dir_ap = "$argv[$ac]"
+
+    else if ( "$argv[$ac]" == "-subj" ) then
+        if ( $ac >= $#argv ) goto FAIL_MISSING_ARG
+        @ ac += 1
+        set subj = "$argv[$ac]"
+
+    # --------- opt
+
+    else if ( "$argv[$ac]" == "-ses" ) then
+        if ( $ac >= $#argv ) goto FAIL_MISSING_ARG
+        @ ac += 1
+        set ses = "$argv[$ac]"
+
+    else if ( "$argv[$ac]" == "-task_label" ) then
+        if ( $ac >= $#argv ) goto FAIL_MISSING_ARG
+        @ ac += 1
+        set task_label = "$argv[$ac]"
+
+    else if ( "$argv[$ac]" == "-template" ) then
+        if ( $ac >= $#argv ) goto FAIL_MISSING_ARG
+        @ ac += 1
+        set template = "$argv[$ac]"
+
+    else
+        echo "\n\n** ERROR: unexpected option #$ac = '$argv[$ac]'\n\n"
+        goto BAD_EXIT
+        
+    endif
+    @ ac += 1
+end
+
+# =======================================================================
+# ======================== ** Verify + setup ** =========================
+# =======================================================================
+
+# check if input dir provided, and its existence
+if ( "${dir_input}" == "" ) then
+    echo "** ERROR: need to provide input dir name with '-dir_input ..'"
+    goto BAD_EXIT
+else if ( ! -d "${dir_input}" ) then
+    echo "** ERROR: invalid input dir via '-dir_input ..'"
+    goto BAD_EXIT
 endif
 
-# full file name for subj (which might optionally include ses)
-set fsubj = ${subj}
+# check if output dir provided, and if it will be/can be overwritten
+if ( "${dir_ap}" == "" ) then
+    echo "** ERROR: need to provide output dir name with '-dir_output ..'"
+    goto BAD_EXIT
+endif
+
+# check if subj ID provided
+if ( "${subj}" == "" ) then
+    echo "** ERROR: need to provide subject ID name with '-subj ..'"
+    goto BAD_EXIT
+endif
+
+# create full file name for subj (which might optionally include ses)
+set fsubj = ${subj}                      # filename : subj[/ses]
+set psubj = ${subj}                      # prefix   : subj[_ses]
 if ( ${ses} != "" ) then
     set fsubj = ${fsubj}/${ses}
+    set psubj = ${psubj}_${ses}
 endif
 
+# verify if subj[/ses] dir exists
+if ( ! -d ${dir_input}/${fsubj} ) then
+    echo "** ERROR: cannot find user-entered subj dir: ${fsubj}"
+    goto BAD_EXIT
+endif
+
+# verify we can find template
+set ok = `@FindAfniDsetPath "${template}"`
+if ( "${ok}" == "" ) then
+    echo "** ERROR: cannot find template: ${template}"
+    goto BAD_EXIT
+endif
+
+# =======================================================================
+
+set ap_label       = 20_ap_simple
+
 # subject directories
-set sdir_basic     = ${dir_basic}/${fsubj}
-set sdir_func      = ${sdir_basic}/func
-set sdir_anat      = ${sdir_basic}/anat
+set sdir_input     = ${dir_input}/${fsubj}
+set sdir_func      = ${sdir_input}/func
+set sdir_anat      = ${sdir_input}/anat
 set sdir_ap        = ${dir_ap}/${fsubj}
 
 # set output directory
@@ -50,15 +151,13 @@ set lab_out  = AP
 setenv AFNI_COMPRESSOR GZIP
 
 # dataset inputs
-set task_label    = "" #task-rest_run-1
-
-set dsets_epi     = ( ${sdir_func}/${subj}*${task_label}*bold.nii* )
-set dset_anat_00  = ( ${sdir_anat}/${subj}*_T1w.nii.gz )
+set dsets_epi     = ( ${sdir_func}/${psubj}*${task_label}*bold.nii* )
+set dset_anat_00  = ( ${sdir_anat}/${psubj}*_T1w.nii.gz )
 
 # want >0 EPI
 if ( ${#dsets_epi} == 0 ) then
     echo "+* ERROR: need at least one EPI"
-    exit 2
+    goto BAD_EXIT
 endif
 
 # only want 1 anatomical
@@ -92,7 +191,7 @@ echo "++ INFO: Using ${nthr_using} of available ${nthr_avail} threads"
 cd ${sdir_out}
 
 # create command script
-set run_script = ap.cmd.${subj}
+set run_script = ap.cmd.${psubj}
 
 cat << EOF >! ${run_script}
 
@@ -100,13 +199,13 @@ cat << EOF >! ${run_script}
 #
 # single-echo FMRI, simple processing for initial QC
 # anatomical has skull on
-# template will be default (MNI*SSW*.nii.gz)
 
 ap_run_simple_rest.tcsh                                                \
     -run_ap                                                            \
     -subjid      ${subj}                                               \
-    -anat        ${dset_anat_00}                                       \
-    -epi         ${dsets_epi}
+    -anat        "${dset_anat_00}"                                     \
+    -epi         ${dsets_epi:q}                                        \
+    -template    "${template}"
 
 EOF
 
@@ -116,7 +215,7 @@ if ( ${status} ) then
 endif
 
 # execute AP command to make processing script
-tcsh -xef ${run_script} |& tee output.ap.cmd.${subj}
+tcsh -xef ${run_script} |& tee output.ap.cmd.${psubj}
 
 if ( ${status} ) then
     set ecode = 2
@@ -125,7 +224,7 @@ endif
 
 
 # execute the proc script, saving text info
-time tcsh -xef proc.${subj} |& tee output.proc.${subj}
+time tcsh -xef proc.${subj} |& tee output.proc.${psubj}
 
 if ( ${status} ) then
     set ecode = 3
@@ -147,3 +246,77 @@ endif
 
 exit ${ecode}
 
+# ========================================================================
+# ========================================================================
+
+SHOW_HELP:
+cat << EOF
+-------------------------------------------------------------------------
+
+Overview ~1~
+
+This is a per-subject script to process a data collection that is in
+BIDS format with a simple form of afni_proc.py. 
+
+Users will probably *not* run this directly, but instead call the
+associated 'run_${ap_label}' script that manages this over a data
+collection.
+
+ver  = ${version}
+auth = PA Taylor (SSCC, NIMH, NIH)
+       Y Halchenko (CON, Dartmouth College)
+-------------------------------------------------------------------------
+
+Options ~1~
+
+-dir_input   DI  :(req) input/top dir of BIDS-format data collection
+
+-dir_output  DO  :(req) output dirname for afni_proc.py BIDS-derivatives
+
+-subj      SUBJ  :(req) subject ID
+
+-ses       SES   : session ID
+
+-task_label TL   : task label string that might be in EPI file names, to help
+                   select a specific set (or subset) of them in func dir
+                   (def: none, so get all dsets in func dir)
+
+-template  TEMPL : template dataset either in local dir, with path, or 
+                   in a place @FindAfniDsetPath can find it
+                   (def: ${template})
+
+-echo            : run very verbosely (with 'set echo' on)
+
+-ver             : display program version
+
+-help            : show help
+
+-hview           : show help in text editor
+
+-------------------------------------------------------------------------
+
+Examples ~1~
+
+1) Basic usage:
+
+   ****
+
+EOF
+
+# ----------------------------------------------------------------------
+
+    goto GOOD_EXIT
+
+SHOW_VERSION:
+   echo "version  $version (${rev_dat})"
+   goto GOOD_EXIT
+
+FAIL_MISSING_ARG:
+    echo "** ERROR: Missing an argument after option flag: '$argv[$ac]'"
+    goto BAD_EXIT
+
+BAD_EXIT:
+    exit 1
+
+GOOD_EXIT:
+    exit 0
